SET SQLBLANKLINES ON;

/* =========================================================
   LIBRARY MANAGEMENT SYSTEM
   Oracle Database 23ai / 26ai
   User: LIBRARY_USER
   Database: FREEPDB1
   Host: localhost:1521
   ========================================================= */

/* Optional Cleanup Script (run if resetting the database):
DROP TABLE ReturnBook CASCADE CONSTRAINTS;
DROP TABLE BorrowBook CASCADE CONSTRAINTS;
DROP TABLE Borrow CASCADE CONSTRAINTS;
DROP TABLE BookAuthor CASCADE CONSTRAINTS;
DROP TABLE Book CASCADE CONSTRAINTS;
DROP TABLE AppUser CASCADE CONSTRAINTS;
DROP TABLE Librarian CASCADE CONSTRAINTS;
DROP TABLE Student CASCADE CONSTRAINTS;
DROP TABLE Author CASCADE CONSTRAINTS;
DROP TABLE BookType CASCADE CONSTRAINTS;
*/

/* =========================================================
   1. BOOKTYPE
   ========================================================= */
CREATE TABLE BookType
(
    BookTypeID     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    BookTypeName   VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_BookType
        PRIMARY KEY (BookTypeID),

    CONSTRAINT UQ_BookType_Name
        UNIQUE (BookTypeName)
);

/* =========================================================
   2. AUTHOR
   ========================================================= */
CREATE TABLE Author
(
    AuthorID       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    AuthorName     VARCHAR2(100) NOT NULL,
    Gender         VARCHAR2(10),
    DOB            DATE,
    POB            VARCHAR2(150),
    Address        VARCHAR2(255),
    Phone          VARCHAR2(30),
    Email          VARCHAR2(100),
    Photo          BLOB,

    CONSTRAINT PK_Author
        PRIMARY KEY (AuthorID),

    CONSTRAINT CK_Author_Gender
        CHECK (Gender IN ('Male', 'Female', 'Other'))
);

/* =========================================================
   3. STUDENT
   ========================================================= */
CREATE TABLE Student
(
    StuID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    StuName        VARCHAR2(100) NOT NULL,
    Gender         VARCHAR2(10),
    DOB            DATE,
    POB            VARCHAR2(150),
    Address        VARCHAR2(255),
    Phone          VARCHAR2(30),
    Email          VARCHAR2(100),
    Photo          BLOB,

    CONSTRAINT PK_Student
        PRIMARY KEY (StuID),

    CONSTRAINT CK_Student_Gender
        CHECK (Gender IN ('Male', 'Female', 'Other'))
);

/* =========================================================
   4. LIBRARIAN
   ========================================================= */
CREATE TABLE Librarian
(
    LibID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    LibName        VARCHAR2(100) NOT NULL,
    Gender         VARCHAR2(10),
    DOB            DATE,
    POB            VARCHAR2(150),
    Address        VARCHAR2(255),
    Phone          VARCHAR2(30),
    Email          VARCHAR2(100),
    Photo          BLOB,

    CONSTRAINT PK_Librarian
        PRIMARY KEY (LibID),

    CONSTRAINT CK_Librarian_Gender
        CHECK (Gender IN ('Male', 'Female', 'Other'))
);

/* =========================================================
   5. BOOK
   ========================================================= */
CREATE TABLE Book
(
    BookID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    BookTitle       VARCHAR2(200) NOT NULL,
    BookTypeID      NUMBER NOT NULL,
    PublishDate     DATE,
    NumOfPages      NUMBER(10),
    NumCopies       NUMBER(10) DEFAULT 0,
    Edition         VARCHAR2(50),
    Publisher       VARCHAR2(150),
    BookSource      VARCHAR2(200),
    Remark          VARCHAR2(500),

    CONSTRAINT PK_Book
        PRIMARY KEY (BookID),

    CONSTRAINT FK_Book_BookType
        FOREIGN KEY (BookTypeID)
        REFERENCES BookType(BookTypeID),

    CONSTRAINT CK_Book_NumPages
        CHECK (NumOfPages IS NULL OR NumOfPages >= 0),

    CONSTRAINT CK_Book_NumCopies
        CHECK (NumCopies >= 0)
);

/* =========================================================
   6. BOOKAUTHOR
   Many-to-Many between BOOK and AUTHOR
   ========================================================= */
CREATE TABLE BookAuthor
(
    BookID          NUMBER NOT NULL,
    AuthorID        NUMBER NOT NULL,
    AuthorDate      DATE,
    Remark          VARCHAR2(500),

    CONSTRAINT PK_BookAuthor
        PRIMARY KEY (BookID, AuthorID),

    CONSTRAINT FK_BookAuthor_Book
        FOREIGN KEY (BookID)
        REFERENCES Book(BookID)
        ON DELETE CASCADE,

    CONSTRAINT FK_BookAuthor_Author
        FOREIGN KEY (AuthorID)
        REFERENCES Author(AuthorID)
        ON DELETE CASCADE
);

/* =========================================================
   7. BORROW
   ========================================================= */
CREATE TABLE Borrow
(
    BorrowID        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    StuID           NUMBER NOT NULL,
    LibID           NUMBER NOT NULL,
    BorrowDate      DATE DEFAULT SYSDATE NOT NULL,
    Remark          VARCHAR2(500),

    CONSTRAINT PK_Borrow
        PRIMARY KEY (BorrowID),

    CONSTRAINT FK_Borrow_Student
        FOREIGN KEY (StuID)
        REFERENCES Student(StuID),

    CONSTRAINT FK_Borrow_Librarian
        FOREIGN KEY (LibID)
        REFERENCES Librarian(LibID)
);

/* =========================================================
   8. BORROWBOOK
   ========================================================= */
CREATE TABLE BorrowBook
(
    BorrowID        NUMBER NOT NULL,
    BookID          NUMBER NOT NULL,
    QtyBorrow       NUMBER(10) DEFAULT 1 NOT NULL,
    IsReturned      NUMBER(1) DEFAULT 0 NOT NULL,
    ReturnDate      DATE,

    CONSTRAINT PK_BorrowBook
        PRIMARY KEY (BorrowID, BookID),

    CONSTRAINT FK_BorrowBook_Borrow
        FOREIGN KEY (BorrowID)
        REFERENCES Borrow(BorrowID)
        ON DELETE CASCADE,

    CONSTRAINT FK_BorrowBook_Book
        FOREIGN KEY (BookID)
        REFERENCES Book(BookID),

    CONSTRAINT CK_BorrowBook_Qty
        CHECK (QtyBorrow > 0),

    CONSTRAINT CK_BorrowBook_Returned
        CHECK (IsReturned IN (0, 1))
);

/* =========================================================
   9. RETURNBOOK
   ========================================================= */
CREATE TABLE ReturnBook
(
    BorrowID        NUMBER NOT NULL,
    BookID          NUMBER NOT NULL,
    LibID           NUMBER NOT NULL,
    QtyReturn       NUMBER(10) DEFAULT 1 NOT NULL,
    ReturnDate      DATE DEFAULT SYSDATE NOT NULL,
    Remark          VARCHAR2(500),

    CONSTRAINT PK_ReturnBook
        PRIMARY KEY (BorrowID, BookID),

    CONSTRAINT FK_ReturnBook_Borrow
        FOREIGN KEY (BorrowID)
        REFERENCES Borrow(BorrowID),

    CONSTRAINT FK_ReturnBook_Book
        FOREIGN KEY (BookID)
        REFERENCES Book(BookID),

    CONSTRAINT FK_ReturnBook_Librarian
        FOREIGN KEY (LibID)
        REFERENCES Librarian(LibID),

    CONSTRAINT CK_ReturnBook_Qty
        CHECK (QtyReturn > 0)
);

/* =========================================================
   10. APPUSER
   ========================================================= */
CREATE TABLE AppUser
(
    LibID           NUMBER NOT NULL,
    UserName        VARCHAR2(100) NOT NULL,
    UserPassword    VARCHAR2(255) NOT NULL,
    UserType        VARCHAR2(30) NOT NULL,

    CONSTRAINT PK_AppUser
        PRIMARY KEY (LibID),

    CONSTRAINT UQ_AppUser_UserName
        UNIQUE (UserName),

    CONSTRAINT FK_AppUser_Librarian
        FOREIGN KEY (LibID)
        REFERENCES Librarian(LibID)
        ON DELETE CASCADE
);
