SET SQLBLANKLINES ON;

/* =============================================================================
   SCRIPT 01: CREATE DATABASE TABLES, CONSTRAINTS & INDEXES
   Project: Library Management System
   DBMS: Oracle Database 23ai / 26ai Free (Docker)
   Schema User: LIBRARY_USER
   ============================================================================= */

/* -----------------------------------------------------------------------------
   0. CLEANUP (Drop tables if they exist in reverse dependency order)
   ----------------------------------------------------------------------------- */
BEGIN
    FOR cur_rec IN (
        SELECT table_name 
        FROM user_tables 
        WHERE table_name IN (
            'BOOK_RETURN', 'BORROWBOOK', 'BORROW', 'BOOKAUTHOR', 
            'BOOK', 'APP_USER', 'LIBRARIAN', 'STUDENT', 'AUTHOR', 'BOOKTYPE'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

/* -----------------------------------------------------------------------------
   1. BOOKTYPE (Parent table for book genres / categories)
   ----------------------------------------------------------------------------- */
CREATE TABLE BookType
(
    BookTypeID     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    BookTypeName   VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_BookType
        PRIMARY KEY (BookTypeID),

    CONSTRAINT UQ_BookType_Name
        UNIQUE (BookTypeName)
);

/* -----------------------------------------------------------------------------
   2. AUTHOR (Book Authors)
   ----------------------------------------------------------------------------- */
CREATE TABLE Author
(
    AuthorID       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    AuthorName     VARCHAR2(100) NOT NULL,
    Gender         VARCHAR2(10),
    DOB            DATE,
    POB            VARCHAR2(150),
    Address        VARCHAR2(255),
    Phone          VARCHAR2(30),
    Email          VARCHAR2(100),
    Photo          BLOB,

    CONSTRAINT PK_Author
        PRIMARY KEY (AuthorID),

    CONSTRAINT CK_Author_Gender
        CHECK (Gender IN ('Male', 'Female', 'Other'))
);

/* -----------------------------------------------------------------------------
   3. STUDENT (Library Members / Borrowers)
   ----------------------------------------------------------------------------- */
CREATE TABLE Student
(
    StuID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    StuName        VARCHAR2(100) NOT NULL,
    Gender         VARCHAR2(10),
    DOB            DATE,
    POB            VARCHAR2(150),
    Address        VARCHAR2(255),
    Phone          VARCHAR2(30),
    Email          VARCHAR2(100),
    Photo          BLOB,

    CONSTRAINT PK_Student
        PRIMARY KEY (StuID),

    CONSTRAINT CK_Student_Gender
        CHECK (Gender IN ('Male', 'Female', 'Other'))
);

/* -----------------------------------------------------------------------------
   4. LIBRARIAN (Library Staff)
   ----------------------------------------------------------------------------- */
CREATE TABLE Librarian
(
    LibID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    LibName        VARCHAR2(100) NOT NULL,
    Gender         VARCHAR2(10),
    DOB            DATE,
    POB            VARCHAR2(150),
    Address        VARCHAR2(255),
    Phone          VARCHAR2(30),
    Email          VARCHAR2(100),
    Photo          BLOB,

    CONSTRAINT PK_Librarian
        PRIMARY KEY (LibID),

    CONSTRAINT CK_Librarian_Gender
        CHECK (Gender IN ('Male', 'Female', 'Other'))
);

/* -----------------------------------------------------------------------------
   5. APP_USER (Login credentials, 1-to-1 relationship with Librarian)
   Note: Renamed from USER to APP_USER to avoid Oracle reserved keyword conflict.
   ----------------------------------------------------------------------------- */
CREATE TABLE APP_USER
(
    LibID           NUMBER NOT NULL,
    UserName        VARCHAR2(100) NOT NULL,
    UserPassword    VARCHAR2(255) NOT NULL,
    UserType        VARCHAR2(30) NOT NULL,

    CONSTRAINT PK_APP_USER
        PRIMARY KEY (LibID),

    CONSTRAINT UQ_APP_USER_UserName
        UNIQUE (UserName),

    CONSTRAINT FK_APP_USER_Librarian
        FOREIGN KEY (LibID)
        REFERENCES Librarian(LibID)
        ON DELETE CASCADE
);

/* -----------------------------------------------------------------------------
   6. BOOK (Book catalog)
   ----------------------------------------------------------------------------- */
CREATE TABLE Book
(
    BookID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    BookTitle       VARCHAR2(200) NOT NULL,
    BookTypeID      NUMBER NOT NULL,
    PublishDate     DATE,
    NumOfPages      NUMBER(10),
    NumCopies       NUMBER(10) DEFAULT 0 NOT NULL,
    Edition         VARCHAR2(50),
    Publisher       VARCHAR2(150),
    BookSource      VARCHAR2(200),
    Remark          VARCHAR2(500),

    CONSTRAINT PK_Book
        PRIMARY KEY (BookID),

    CONSTRAINT FK_Book_BookType
        FOREIGN KEY (BookTypeID)
        REFERENCES BookType(BookTypeID),

    CONSTRAINT CK_Book_NumPages
        CHECK (NumOfPages IS NULL OR NumOfPages >= 0),

    CONSTRAINT CK_Book_NumCopies
        CHECK (NumCopies >= 0)
);

/* -----------------------------------------------------------------------------
   7. BOOKAUTHOR (Many-to-Many junction between Book and Author)
   ----------------------------------------------------------------------------- */
CREATE TABLE BookAuthor
(
    BookID          NUMBER NOT NULL,
    AuthorID        NUMBER NOT NULL,
    AuthorDate      DATE,
    Remark          VARCHAR2(500),

    CONSTRAINT PK_BookAuthor
        PRIMARY KEY (BookID, AuthorID),

    CONSTRAINT FK_BookAuthor_Book
        FOREIGN KEY (BookID)
        REFERENCES Book(BookID)
        ON DELETE CASCADE,

    CONSTRAINT FK_BookAuthor_Author
        FOREIGN KEY (AuthorID)
        REFERENCES Author(AuthorID)
        ON DELETE CASCADE
);

/* -----------------------------------------------------------------------------
   8. BORROW (Borrow transaction header)
   ----------------------------------------------------------------------------- */
CREATE TABLE Borrow
(
    BorrowID        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    StuID           NUMBER NOT NULL,
    LibID           NUMBER NOT NULL,
    BorrowDate      DATE DEFAULT SYSDATE NOT NULL,
    Remark          VARCHAR2(500),

    CONSTRAINT PK_Borrow
        PRIMARY KEY (BorrowID),

    CONSTRAINT FK_Borrow_Student
        FOREIGN KEY (StuID)
        REFERENCES Student(StuID),

    CONSTRAINT FK_Borrow_Librarian
        FOREIGN KEY (LibID)
        REFERENCES Librarian(LibID)
);

/* -----------------------------------------------------------------------------
   9. BORROWBOOK (Borrow transaction line items)
   Composite primary key: (BorrowID, BookID)
   ----------------------------------------------------------------------------- */
CREATE TABLE BorrowBook
(
    BorrowID        NUMBER NOT NULL,
    BookID          NUMBER NOT NULL,
    QtyBorrow       NUMBER(10) DEFAULT 1 NOT NULL,
    IsReturned      NUMBER(1) DEFAULT 0 NOT NULL,
    ReturnDate      DATE,

    CONSTRAINT PK_BorrowBook
        PRIMARY KEY (BorrowID, BookID),

    CONSTRAINT FK_BorrowBook_Borrow
        FOREIGN KEY (BorrowID)
        REFERENCES Borrow(BorrowID)
        ON DELETE CASCADE,

    CONSTRAINT FK_BorrowBook_Book
        FOREIGN KEY (BookID)
        REFERENCES Book(BookID),

    CONSTRAINT CK_BorrowBook_Qty
        CHECK (QtyBorrow > 0),

    CONSTRAINT CK_BorrowBook_Returned
        CHECK (IsReturned IN (0, 1))
);

/* -----------------------------------------------------------------------------
   10. BOOK_RETURN (Return transactions)
   Note: Named BOOK_RETURN instead of RETURN (Oracle reserved word).
   Design decision: Uses a surrogate ReturnID identity primary key while keeping
   BorrowID, BookID, and LibID as foreign keys. This allows multiple partial returns
   over time for a borrowed book without violating a composite (BorrowID, BookID) PK.
   ----------------------------------------------------------------------------- */
CREATE TABLE BOOK_RETURN
(
    ReturnID        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    BorrowID        NUMBER NOT NULL,
    BookID          NUMBER NOT NULL,
    LibID           NUMBER NOT NULL,
    QtyReturn       NUMBER(10) DEFAULT 1 NOT NULL,
    ReturnDate      DATE DEFAULT SYSDATE NOT NULL,
    Remark          VARCHAR2(500),

    CONSTRAINT PK_BOOK_RETURN
        PRIMARY KEY (ReturnID),

    CONSTRAINT FK_BOOK_RETURN_Borrow
        FOREIGN KEY (BorrowID)
        REFERENCES Borrow(BorrowID),

    CONSTRAINT FK_BOOK_RETURN_Book
        FOREIGN KEY (BookID)
        REFERENCES Book(BookID),

    CONSTRAINT FK_BOOK_RETURN_Librarian
        FOREIGN KEY (LibID)
        REFERENCES Librarian(LibID),

    CONSTRAINT CK_BOOK_RETURN_Qty
        CHECK (QtyReturn > 0)
);

/* -----------------------------------------------------------------------------
   11. PERFORMANCE INDEXES (Foreign keys and commonly queried columns)
   ----------------------------------------------------------------------------- */
CREATE INDEX IDX_Student_Name       ON Student(StuName);
CREATE INDEX IDX_Author_Name        ON Author(AuthorName);
CREATE INDEX IDX_Book_Title         ON Book(BookTitle);
CREATE INDEX IDX_Book_BookTypeID    ON Book(BookTypeID);
CREATE INDEX IDX_Borrow_StuID       ON Borrow(StuID);
CREATE INDEX IDX_Borrow_LibID       ON Borrow(LibID);
CREATE INDEX IDX_BorrowBook_BookID  ON BorrowBook(BookID);
CREATE INDEX IDX_Return_BorrowID    ON BOOK_RETURN(BorrowID);
CREATE INDEX IDX_Return_BookID      ON BOOK_RETURN(BookID);
CREATE INDEX IDX_Return_LibID       ON BOOK_RETURN(LibID);
